# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
  
- script: |
    npx scriptless-cli run --cloudURL "https://demo.app.perfectomobile.com" --securityToken "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI4YmI4YmZmZS1kMzBjLTQ2MjctYmMxMS0zNTYyMmY1ZDkyMGYifQ.eyJpYXQiOjE2MzM2MDc5MDYsImp0aSI6IjFhOGMwM2RmLTUyMGUtNGIwYi05NjQxLTRmMTdkOWY0YzczYiIsImlzcyI6Imh0dHBzOi8vYXV0aC5wZXJmZWN0b21vYmlsZS5jb20vYXV0aC9yZWFsbXMvZGVtby1wZXJmZWN0b21vYmlsZS1jb20iLCJhdWQiOiJodHRwczovL2F1dGgucGVyZmVjdG9tb2JpbGUuY29tL2F1dGgvcmVhbG1zL2RlbW8tcGVyZmVjdG9tb2JpbGUtY29tIiwic3ViIjoiZDQyMTczM2MtOTFjOC00YzIxLTgxZmItZmM3OWFlNzRjZmQwIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6Im9mZmxpbmUtdG9rZW4tZ2VuZXJhdG9yIiwibm9uY2UiOiJkY2ZhMDc5Ni05ZWJhLTQxYmYtOThhNi1hODJkMGNlMjAzZWMiLCJzZXNzaW9uX3N0YXRlIjoiYThmNDI0YzktYTM4OC00MmU3LWE3OWUtY2JmNDI1MWRjOWU5Iiwic2NvcGUiOiJvcGVuaWQgb2ZmbGluZV9hY2Nlc3MifQ.azZ-UFTSrrNEVeVUbB7yHjBwd43gJfk3j9zDVAoZ3tI" -p "Salesforce" -v "Base" -j "Salesforce Parallel Job" -l "Chrome 1024x768" -e "https://login.salesforce.com(Default)" -c vsts -r TEST-1.xml
  displayName: 'run scriptless'